UserManagement/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import RegistrationView, LoginView, LogoutView,ChangePasswordView, UserListView, CustomUsersUpdateAPIView, UserDetailAPIView, PasswordResetRequestView, PasswordResetConfirmView, CustomUsersDeleteAPIView, CheckUserExistsView
from rest_framework_simplejwt import views as jwt_views
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

app_name = 'UserManagement'

urlpatterns = [
    path('register', RegistrationView.as_view(), name='register'),
    path('user-list', UserListView.as_view(), name='user_list'),
    path('user/update/<int:pk>/', CustomUsersUpdateAPIView.as_view(), name='user_update'),
    path('user/delete/<int:pk>/', CustomUsersDeleteAPIView.as_view(), name='delete_user'),
    path('user/<int:pk>/', UserDetailAPIView.as_view(), name='user_detail'),
    path('check-user-exists/', CheckUserExistsView.as_view(), name='check_user_exists'),
    path('', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('change-password', ChangePasswordView.as_view(), name='change_password'),
    path('token-refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('password-reset/', PasswordResetRequestView.as_view(), name='password-reset-request'),
    path('password-reset-confirm/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WastePlasticCollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('UserManagement.urls')),
    path('api/', include('WastePlasticCollectorApp.urls')),
]

UserManagement/forms.py
# from django.contrib import admin
# from django.contrib.auth.models import Group
# from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
# from django.contrib.auth.forms import ReadOnlyPasswordHashField
# from django.core.exceptions import ValidationError
# from django import forms
# from .models import CustomUsers


# class UserCreationForm(forms.ModelForm):
#     password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
#     password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

#     class Meta:
#         model = CustomUsers
#         fields = ('email',  'phone_number', 'profile_photo', 'role', 'user_status', 'country', 'region', 'zone', 'woreda', 'kebele', 'role')

#     def clean_password2(self):
#         # Check that the two password entries match
#         password1 = self.cleaned_data.get("password1")
#         password2 = self.cleaned_data.get("password2")
#         if password1 and password2 and password1 != password2:
#             raise ValidationError("Passwords don't match")
#         return password2

#     def save(self, commit=True):
#         # Save the provided password in hashed format
#         user = super().save(commit=False)
#         user.set_password(self.cleaned_data["password1"])
#         if commit:
#             user.save()
#         return user


# class UserChangeForm(forms.ModelForm):
#     password = ReadOnlyPasswordHashField()

#     class Meta:
#         model = CustomUsers
#         fields = ('email', 'password', 'phone_number','profile_photo', 'role', 'is_active', 'is_admin')

#     def clean_password(self):
#         return self.initial["password"]


# class UserAdmin(BaseUserAdmin):
#     form = UserChangeForm
#     add_form = UserCreationForm

#     list_display = ('email', 'phone_number', 'profile_photo', 'role', 'user_status', 'country', 'region', 'zone', 'woreda', 'kebele', 'role', 'is_admin', 'is_active')
#     list_filter = ('is_admin', )
#     fieldsets = (
#         (None, {'fields': ('email', 'password')}),
#         ('Personal info', {'fields': ('phone_number', 'profile_photo', 'role', 'user_status', 'country', 'region', 'zone', 'woreda', 'kebele', 'role')}),
#         ('Permissions', {'fields': ('is_admin', 'is_active')}),
#     )
#     add_fieldsets = (
#         (None, {
#             'classes': ('wide',),
#             'fields': ('email', 'password1', 'password2', 'phone_number', 'profile_photo', 'role', 'user_status', 'country', 'region', 'zone', 'woreda', 'kebele', 'role', 'is_admin', 'is_active'),
#         }),
#     )
#     search_fields = ('email',)
#     ordering = ('email',)
#     filter_horizontal = ()


# admin.site.register(CustomUsers, UserAdmin)
from django.contrib import admin
from django.contrib.auth.models import Group
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError
from django import forms
from .models import CustomUsers


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = CustomUsers
        fields = ('email', 'name', 'phone_number', 'profile_photo', 'country', 'region', 'zone', 'woreda', 'kebele', 'role')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = CustomUsers
        fields = ('email', 'password', 'phone_number', 'is_active', 'is_admin')

    def clean_password(self):
        return self.initial["password"]


class UserAdmin(BaseUserAdmin):
    form = UserChangeForm
    add_form = UserCreationForm

    list_display = ('email', 'name', 'phone_number', 'profile_photo', 'country', 'region', 'zone', 'woreda', 'kebele', 'role', 'is_admin', 'is_active')
    list_filter = ('is_admin', )
    fieldsets = (
        (None, {'fields': ('email', 'password')}),
        ('Personal info', {'fields': ('name', 'phone_number', 'profile_photo', 'country', 'region', 'zone', 'woreda', 'kebele', 'role')}),
        ('Permissions', {'fields': ('is_admin', 'is_active')}),
    )
    add_fieldsets = (
        (None, {
            'classes': ('wide',),
            'fields': ('email', 'password1', 'password2', 'name', 'phone_number', 'profile_photo', 'country', 'region', 'zone', 'woreda', 'kebele', 'role', 'is_admin', 'is_active'),
        }),
    )
    search_fields = ('email',)
    ordering = ('email',)
    filter_horizontal = ()


admin.site.register(CustomUsers, UserAdmin)

UserManagement/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.backends import ModelBackend
from django.http import HttpResponse
from rest_framework_simplejwt.authentication import JWTAuthentication
from rest_framework import generics, status, authentication, permissions
from rest_framework.authentication import TokenAuthentication, SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import  Response
from rest_framework.views import APIView
from rest_framework.generics import ListAPIView
from .utils import get_tokens_for_user
from .serializers import RegistrationSerializer, PasswordChangeSerializer, CustomUsersUpdateSerializer,CustomUsersUpdateSerializer, CustomUsersDetailSerializer, PasswordResetSerializer, PasswordResetConfirmSerializer, CustomUsersDeleteSerializer
from rest_framework_simplejwt.tokens import RefreshToken
# from rest_framework.authtoken.models import Token
from .models import CustomUsers
# Create your views here.

class RegistrationView(APIView):
    authentication_classes = []
    permission_classes = []
    def get(self, request):
        return render(request, 'UserManagement/user_registration.html')

    def post(self, request):
        try:
            serializer = RegistrationSerializer(data=request.data)
            if serializer.is_valid():
                user = serializer.save()
                return Response({
                    'success': True, 
                    'success_message': "User created successfully!", 
                    'data': {
                        'id': user.id,
                        **serializer.data
                    }
                }, status=status.HTTP_201_CREATED)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        except Exception as e:
            return Response({
                'success': False,
                'message': 'Failed to register user',
                'error': str(e)
            }, status=status.HTTP_500_INTERNAL_SERVER_ERROR)



class UserListView(ListAPIView):
    permission_classes = [permissions.IsAuthenticated]
    authentication_classes = [JWTAuthentication]
    queryset = CustomUsers.objects.all()
    serializer_class = RegistrationSerializer


class CustomUsersUpdateAPIView(generics.RetrieveUpdateAPIView):
    permission_classes = [permissions.IsAuthenticated]
    authentication_classes = [JWTAuthentication]
    queryset = CustomUsers.objects.all()
    serializer_class = CustomUsersUpdateSerializer
    partial = True

    def update(self, request, *args, **kwargs):
        try:
            partial = kwargs.pop('partial', False)
            instance = self.get_object()
            serializer = self.get_serializer(instance, data=request.data, partial=partial)
            serializer.is_valid(raise_exception=True)
            self.perform_update(serializer)
            return Response({
                'success': True,
                'message': 'User updated successfully',
                'data': serializer.data
            })
        except Exception as e:
            return Response({
                'success': False,
                'message': 'Failed to update user',
                'error': str(e)
            }, status=status.HTTP_400_BAD_REQUEST)


class CustomUsersDeleteAPIView(generics.RetrieveDestroyAPIView):
    permission_classes = [permissions.IsAuthenticated]
    authentication_classes = [JWTAuthentication]
    queryset = CustomUsers.objects.all()
    serializer_class = CustomUsersDeleteSerializer

    def delete(self, request, *args, **kwargs):
        try:
            instance = self.get_object()
            self.perform_destroy(instance)
            return Response({
                'success': True,
                'message': 'User deleted successfully'
            }, status=status.HTTP_200_OK)
        except CustomUsers.DoesNotExist:
            return Response({
                'success': False,
                'error': 'User not found'
            }, status=status.HTTP_404_NOT_FOUND)
        except Exception as e:
            return Response({
                'success': False,
                'message': 'Failed to delete user',
                'error': str(e)
            }, status=status.HTTP_400_BAD_REQUEST)

    def perform_destroy(self, instance):
        instance.delete()


class CheckUserExistsView(APIView):
    """
    Endpoint to check if a user exists based on email or phoneNumber.
    """
    authentication_classes = []
    permission_classes = []

    def post(self, request):
        # Get the email or username from the request data
        identifier = request.data.get('email') or request.data.get('phone_number')
        
        if not identifier:
            return Response({
                'success': False,
                'message': 'Email or Username is required.'
            }, status=status.HTTP_400_BAD_REQUEST)

        # Check if the user exists
        user_exists = CustomUsers.objects.filter(email=identifier).exists() or \
                      CustomUsers.objects.filter(phone_number=identifier).exists()

        if user_exists:
            return Response({
                'success': True,
                'message': 'User exists.'
            }, status=status.HTTP_200_OK)

        return Response({
            'success': False,
            'message': 'User does not exist.'
        }, status=status.HTTP_404_NOT_FOUND)


class LoginView(APIView):
    def get(self, request):
        return render(request, 'UserManagement/login.html')
    def post(self, request):
        if 'username' not in request.data or 'password' not in request.data:
            return Response({'message': 'Credentials missing'}, status=status.HTTP_400_BAD_REQUEST)

        username = request.data['username']
        password = request.data['password']
        
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)            
            auth_data = get_tokens_for_user(request.user)
            response = Response({
                'message': 'Login Success', 
                'id': user.id, 
                'username': user.email, 
                'name': user.name,
                'phone_number': user.phone_number,
                'profile_photo': user.profile_photo.url if user.profile_photo else None,
                'user_status': user.user_status,
                'role': user.role,
                **auth_data}, status=status.HTTP_200_OK)

            # Set tokens as cookies
            response.set_cookie('access_token', auth_data['access_token'], httponly=True)
            response.set_cookie('refresh_token', auth_data['refresh_token'], httponly=True)

            return response
        return Response({'msg': 'Invalid Credentials'}, status=status.HTTP_401_UNAUTHORIZED)
      
class LogoutView(APIView):
    def post(self, request):
        logout(request)
        return Response({'msg': 'Successfully Logged out'}, status=status.HTTP_200_OK)


      
class ChangePasswordView(APIView):
    permission_classes = [permissions.IsAuthenticated]
    authentication_classes = [JWTAuthentication]

    def post(self, request):
        try:
            serializer = PasswordChangeSerializer(context={'request': request}, data=request.data)
            serializer.is_valid(raise_exception=True)
            request.user.set_password(serializer.validated_data['new_password'])
            request.user.save()
            return Response({
                'success': True,
                "message": "Password changed successfully.",
                'data': serializer.data
                }, status=status.HTTP_204_NO_CONTENT)
        except Exception as e:
            return Response({
                'success': False,
                "message": "Failed to change password.",
                "error": str(e)
                }, status=status.HTTP_400_BAD_REQUEST)


class UserDetailAPIView(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = [permissions.IsAuthenticated]
    authentication_classes = [JWTAuthentication]
    queryset = CustomUsers.objects.all()
    serializer_class = CustomUsersDetailSerializer

    def retrieve(self, request, *args, **kwargs):
        try:
            instance = self.get_object()
            serializer = self.get_serializer(instance)
            return Response({
                'success': True,
                'message': 'User details retrieved successfully',
                'data': serializer.data
            })
        except Exception as e:
            return Response({
                'success': False,
                'message': 'Failed to retrieve user details',
                'error': str(e)
            }, status=status.HTTP_404_NOT_FOUND)


class PasswordResetRequestView(APIView):
    authentication_classes = []
    permission_classes = []

    def post(self, request):
        serializer = PasswordResetSerializer(data=request.data, context={'request': request})
        if serializer.is_valid():
            serializer.save()
            return Response({'success': True, 'message': 'Password reset link sent'}, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class PasswordResetConfirmView(APIView):
    authentication_classes = []
    permission_classes = []

    def post(self, request):
        serializer = PasswordResetConfirmSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response({'success': True, 'message': 'Password reset successful'}, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

UserManagement/templates/UserManagement/login.html
{% extends 'WastePlasticCollectorApp/base.html' %}
{% block title %}Login{% endblock %}
{% block css %}
<style>
 
  .login-text {
    margin-top: 5px;
    color: #303778;
    font-weight: bold;
    margin-left: 13%;
  }
  .img-fluid{
    margin-left: 0%;
    width: 100%;
    height: 100%;
  }
  .login{
    color: #009973;
  }
  .btn-login{
    color: white;
    background: #009973;
  }
  .btn-login:hover{
    color: white;
    background: #00b386;
  }
  .logo-img{
    margin-left: 20%;
  }
  .logo-img img{
    width: 20%;
    height: 20%;
  }
</style>

{% endblock %}
{% load static %}

{% block content %}
<div class="container mt-0">
    <div class="row">
        <div class="col-lg-6">
            <img src="{% static 'UserManagement/image/garbage-trash.jpg' %}" alt="login logo" class="login-image img-fluid" />
        </div>
        <div class="col-md-6">
            <div class="mb-1 mt-5 logo-img">
                <img src="{% static 'dist/img/clenville_logo.jpg' %}"
                alt="AdminLTE Logo" />
            </div>
            <div class="mb-1">
                <h1 class="login-text">We Collect</h1>
            </div><br><br>
            <h1 class="text-bold login">Login</h1>
            <p>Login into your account!</p>
            <form id="loginForm" method="post" action="{% url 'UserManagement:login' %}">
                {% csrf_token %}
                <div class="mb-4 form-group row">
                    <div class="col-md-8">
                        <label for="username" class="form-label">Username</label>
                        <input type="text" name="username" id="username" class="form-control" required>
                    </div>
                </div>
                <div class="mb-4 form-group row">
                    <div class="col-md-8">
                        <label for="password" class="form-label">Password</label>
                        <input type="password" name="password" id="password" class="form-control" required>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8">
                        <button type="submit" class="btn btn-login form-control">Login</button>
                    </div>
                </div>
            </form>
            <p>Not a user yet? <a href="{% url 'UserManagement:register' %}">Request credentials</a></p>
        </div>
    </div>
</div>
{% endblock content %}

{% block custom_js %}
<script>
    document.getElementById("loginForm").addEventListener("submit", function(event) {
        event.preventDefault();
        const formData = new FormData(event.target);
        const url = event.target.action;

        const options = {
            method: "POST",
            body: formData,
            headers: {
                "X-CSRFToken": "{{ csrf_token }}"
            }
        };

        fetch(url, options)
            .then(response => {
                if (response.ok) {
                    window.location.href = "{% url 'dashboard' %}";
                } else {
                    console.error('Login failed:', response.statusText);
                }
            })
            .catch(error => console.error('Error during login:', error));
    });
</script>
{% endblock custom_js %}

UserManagement/templates/UserManagement/user_registration.html
{% extends 'WastePlasticCollectorApp/base.html' %}
{% block title %}User Registration{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center">User Registration</h1>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form id="registrationForm" method="post" action="http://localhost:8000/register">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" name="email" id="email" class="form-control" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" name="password" id="password" class="form-control" required>
                </div>
                <div class="mb-3">
                    <label for="password2" class="form-label">Confirm Password</label>
                    <input type="password" name="password2" id="password2" class="form-control" required>
                </div>
                <div class="mb-3">
                    <label for="first_name" class="form-label">First Name</label>
                    <input type="text" name="first_name" id="first_name" class="form-control" required>
                </div>
                <div class="mb-3">
                    <label for="last_name" class="form-label">Last Name</label>
                    <input type="text" name="last_name" id="last_name" class="form-control" required>
                </div>
                <div class="mb-3">
                    <label for="phone_number" class="form-label">Phone Number</label>
                    <input type="text" name="phone_number" id="phone_number" class="form-control" required>
                </div>
                <div class="mb-3">
                    <label for="country" class="form-label">Country</label>
                    <input type="text" name="country" id="country" class="form-control" required>
                </div>
                <div class="mb-3">
                    <label for="region" class="form-label">Region</label>
                    <input type="text" name="region" id="region" class="form-control" required>
                </div>
                <div class="mb-3">
                    <label for="zone" class="form-label">Zone</label>
                    <input type="text" name="zone" id="zone" class="form-control" required>
                </div>
                <div class="mb-3">
                    <label for="woreda" class="form-label">Woreda</label>
                    <input type="text" name="woreda" id="woreda" class="form-control" required>
                </div>
                <div class="mb-3">
                    <label for="kebele" class="form-label">Kebele</label>
                    <input type="text" name="kebele" id="kebele" class="form-control" required>
                </div>
                <div class="mb-3">
                    <label for="role" class="form-label">Role</label>
                    <input type="text" name="role" id="role" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary">Register</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block js_script %}
<script>
    document.getElementById("registrationForm").addEventListener("submit", function(event) {
        // Prevent default form submission behavior
        event.preventDefault();

        // Fetch form data
        const formData = new FormData(event.target);

        // Fetch registration endpoint URL
        const url = event.target.action;

        // Fetch options for the fetch request
        const options = {
            method: "POST",
            body: formData,
            headers: {
                "X-CSRFToken": "{{ csrf_token }}"
            }
        };

        // Send fetch request to registration endpoint
        fetch(url, options)
            .then(response => {
                if (response.ok) {
                    // Redirect to a success page or perform any other action upon successful registration
                    console.log('Registration successful');
                } else {
                    console.error('Registration failed:', response.statusText);
                }
            })
            .catch(error => console.error('Error during registration:', error));
    });
</script>
{% endblock %}